[package]
name = "plecakpkg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
cmake = "0.1.54"
git2 = "0.20.2"
serde = "1.0.226"
serde_yaml = "0.9.34"
tokio = "1.47.1"
